#include <stdio.h>
#include "define.h"
 
#define TEST_MMC_DDR3_PHY 
#define TEST_MMC_DDR3_PHY_FMC
#define TEST_MMC_DDR3_PHY_TWI
#define GISC_CODE_LENGTH 0x1000 
#define GISC_CODE_PER_BLK 0x20
#define GISC_CLEAN_POS 0xfff200 
#define GISC_CLEAN_MAX 0x200 
#define GISC_PM_POS 0xfff100 
#define GISC_SG_POS 0xfff200 
#define GISC_CD_POS 0xfff300 
#define GISC_PM_MAX 0x100 
#define GISC_SG_MAX 0x100 

FILE *fp;
unsigned int line = 0;
unsigned int tmpLine = 0;
unsigned int jmpLine0 = 0;
unsigned int jmpLine1 = 0;
unsigned int jmpLine2 = 0;
unsigned int jmpLine3 = 0;
unsigned int jmpLine4 = 0;
unsigned int jmpLine5 = 0;
unsigned int jmpLine6 = 0;
unsigned int jmpLine7 = 0;
unsigned int jmpLine8 = 0;
unsigned int jmpLine9 = 0;
unsigned int jmpLineSyn = 0;
static void openFile();
void convertX(unsigned long a, unsigned long b, unsigned int c);
void convertB(unsigned long a, unsigned long b, unsigned int c);
void convertJ();
void convertLog(unsigned int a,unsigned int b,unsigned int c);
void code_testDDR(){
	
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	jmpLine1 = line; 
	convertX(OP_SET,SG_DDR_WRITE_0,0x11111111);
	convertX(OP_SET,SG_DDR_WRITE_1,0x33333333);
	convertX(OP_SET,SG_DDR_WRITE_2,0x55555555);
	convertX(OP_SET,SG_DDR_WRITE_3,0x77777777);
	convertX(OP_SET,SG_DDR_WRITE_4,0x99999999);
	convertX(OP_SET,SG_DDR_WRITE_5,0xaaaaaaaa);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE);
	
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_DDR_READ_0);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x1);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_DDR_READ_1);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x1);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_DDR_READ_2);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x1);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_DDR_READ_3);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x1);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_DDR_READ_4);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x1);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_DDR_READ_5);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x1);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	tmpLine = line;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
}
void code_loadMMC(){
	convertX(OP_SET,SG_REGVAL0,0x1f);
	jmpLine2 = line;
	convertX(OP_SET,SG_2BIT_GROUP_SET_MMC_OP,SG_MMC_OP_READ);
	convertX(OP_SET,SG_2BIT_GROUP_SET_MMC_OP,SG_MMC_OP_IDLE);
	
	jmpLine0 = line;
	convertX(OP_PHY,SG_PARA0_A0,PM_1BIT_GROUP_SET);
	convertX(OP_SET,SG_PARA0_B0,PM_1BIT_G0_MMC_ACT_IDLE);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_MASK_AND);
	convertX(OP_PHY,SG_PARA0_A0,PM_PARA0_C);
	convertX(OP_SET,SG_PARA0_B0,PM_1BIT_G0_MMC_ACT_IDLE);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	
	tmpLine = line+0x5;
	
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLine0);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
}
void code_writeDDR(){
	
	
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	
	jmpLine1 = line; 
	convertX(OP_SET,SG_1BIT_GROUP_SET,SG_1BIT_G0_MMC_FIFO_RO);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_PHY,SG_DDR_WRITE_1,PM_MMC_DATA_READ);
	convertX(OP_SET,SG_1BIT_GROUP_SET,SG_1BIT_G0_MMC_FIFO_RO);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_PHY,SG_DDR_WRITE_2,PM_MMC_DATA_READ);
	convertX(OP_SET,SG_1BIT_GROUP_SET,SG_1BIT_G0_MMC_FIFO_RO);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_PHY,SG_DDR_WRITE_3,PM_MMC_DATA_READ);
	convertX(OP_SET,SG_1BIT_GROUP_SET,SG_1BIT_G0_MMC_FIFO_RO);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_PHY,SG_DDR_WRITE_4,PM_MMC_DATA_READ);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	
	convertX(OP_CPY,SG_PARA0_A0,SG_DDR_ADDR);
	
	convertX(OP_CPY,SG_PARA0_B0,SG_REGVAL0);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	convertX(OP_CPY,SG_PARA0_A0,SG_DDR_ADDR);
	convertX(OP_SET,SG_PARA0_B0,0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_DDR_ADDR,PM_PARA0_C);
	
	tmpLine = line +0x5;
	
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLine1);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
}
void code_checkMMC_max(){
	
	
	convertX(OP_CPY,SG_PARA0_A0,SG_MMC_ADDR);
	
	
	convertX(OP_SET,SG_PARA0_B0,GISC_CODE_LENGTH-0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	tmpLine = line + 0xd;
	
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	convertX(OP_CPY,SG_PARA0_A0,SG_MMC_ADDR);
	convertX(OP_SET,SG_PARA0_B0,0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_MMC_ADDR,PM_PARA0_C);
	convertX(OP_CPY,SG_PARA0_A0,SG_REGVAL0);
	convertX(OP_SET,SG_PARA0_B0,GISC_CODE_PER_BLK);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_REGVAL0,PM_PARA0_C);
	
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLine2);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	
	
	
	
	
	
}
void code_printOut(){
	
	convertX(OP_SET,SG_DDR_ADDR,0x0); 
	jmpLine3 = line;
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE);
	
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_DDR_READ_2);
	
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x1);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_CPY,SG_PARA0_A0,SG_8BIT_GROUP_SET_TX0);
	convertX(OP_SET,SG_PARA0_B0,0x100);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_DIV);
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_DDR_READ_3);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x1);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_CPY,SG_PARA0_A0,SG_8BIT_GROUP_SET_TX0);
	convertX(OP_SET,SG_PARA0_B0,0x100);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_DIV);
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_DDR_READ_4);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x1);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_CPY,SG_PARA0_A0,SG_8BIT_GROUP_SET_TX0);
	convertX(OP_SET,SG_PARA0_B0,0x100);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_DIV);
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_DDR_READ_5);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x1);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_DDR_READ_5);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_CPY,SG_PARA0_A0,SG_8BIT_GROUP_SET_TX0);
	convertX(OP_SET,SG_PARA0_B0,0x100);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_DIV);
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_PARA0_C);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_CPY,SG_PARA0_A0,SG_8BIT_GROUP_SET_TX0);
	convertX(OP_SET,SG_PARA0_B0,0x100);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_DIV);
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_PARA0_C);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_CPY,SG_PARA0_A0,SG_8BIT_GROUP_SET_TX0);
	convertX(OP_SET,SG_PARA0_B0,0x100);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_DIV);
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_PARA0_C);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	
	convertX(OP_CPY,SG_PARA0_A0,SG_DDR_ADDR);
	
	convertX(OP_SET,SG_PARA0_B0,0x3f);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	tmpLine = line + 0x9;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	convertX(OP_CPY,SG_PARA0_A0,SG_DDR_ADDR);
	convertX(OP_SET,SG_PARA0_B0,0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_DDR_ADDR,PM_PARA0_C);
	
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLine3);
	
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	
	convertX(OP_SET,SG_DDR_ADDR,GISC_CLEAN_POS); 
	jmpLine4 = line;
	convertX(OP_SET,SG_DDR_WRITE_1,0x0);
	convertX(OP_SET,SG_DDR_WRITE_2,0x0);
	convertX(OP_SET,SG_DDR_WRITE_3,0x0);
	convertX(OP_SET,SG_DDR_WRITE_4,0x0);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	
	convertX(OP_CPY,SG_PARA0_A0,SG_DDR_ADDR);
	
	convertX(OP_SET,SG_PARA0_B0,GISC_CLEAN_POS+GISC_CLEAN_MAX-0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	tmpLine = line +0x9;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	convertX(OP_CPY,SG_PARA0_A0,SG_DDR_ADDR);
	convertX(OP_SET,SG_PARA0_B0,0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_DDR_ADDR,PM_PARA0_C);
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLine4);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
}
void code_sg_pm(){
	
	
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x0); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x0,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x1); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x1,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x2); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x2,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x3); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x3,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x4); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x4,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x5); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x5,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x6); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x6,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x7); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x7,PM_DDR_READ_5);
	
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x8); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x8,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x9); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x9,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0xa); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0xa,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0xb); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0xb,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0xc); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0xc,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0xd); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0xd,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0xe); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0xe,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0xf); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0xf,PM_DDR_READ_5);
	
	
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x10); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x10,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x11); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x11,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x12); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x12,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x13); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x13,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x14); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x14,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x15); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x15,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x16); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x16,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x17); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x17,PM_DDR_READ_5);
	
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x18); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x18,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x19); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x19,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x1a); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x1a,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x1b); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x1b,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x1c); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x1c,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x1d); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x1d,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x1e); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x1e,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x1f); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x1f,PM_DDR_READ_5);
	
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x20); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x20,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x21); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x21,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x22); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x22,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x23); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x23,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x24); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x24,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x25); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x25,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x26); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x26,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x27); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x27,PM_DDR_READ_5);
	
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x28); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x28,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x29); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x29,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x2a); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x2a,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x2b); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x2b,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x2c); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x2c,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x2d); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x2d,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x2e); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x2e,PM_DDR_READ_5);
	convertX(OP_SET,SG_DDR_ADDR,GISC_SG_POS+0x2f); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,0x2f,PM_DDR_READ_5);
	
	
	
	
	
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x0); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x0);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x1); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x1);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x2); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x2);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x3); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x3);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x4); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x4);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x5); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x5);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x6); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x6);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x7); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x7);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	
	
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x8); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x8);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x9); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x9);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0xa); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0xa);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0xb); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0xb);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0xc); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0xc);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0xd); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0xd);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0xe); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0xe);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0xf); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0xf);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	
	
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x10); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x10);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x11); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x11);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x12); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x12);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x13); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x13);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x14); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x14);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x15); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x15);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x16); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x16);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x17); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x17);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	
	
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x18); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x18);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x19); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x19);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x1a); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x1a);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x1b); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x1b);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x1c); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x1c);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x1d); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x1d);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x1e); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x1e);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_PM_POS+0x1f); 
	convertX(OP_PHY,SG_DDR_WRITE_4,0x1f);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	
}
void code_fetch_op(){
	
	
	
	convertX(OP_SET,SG_DDR_ADDR,GISC_CD_POS+0x0); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,SG_DDR_ADDR,PM_DDR_READ_5);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	
	
	
	
	
	
	convertX(OP_SET,SG_PARA0_S,0x0);
	convertX(OP_SET,SG_PARA0_S,0x0);
	convertX(OP_SET,SG_PARA0_S,0x0);
	convertX(OP_SET,SG_PARA0_S,0x0);
	convertX(OP_SET,SG_PARA0_S,0x0);
	
	convertX(OP_PHY,SG_REGVAL0,PM_DDR_READ_4);
	convertX(OP_PHY,SG_PARA0_A0,PM_DDR_READ_2);
}
void code_runtime(){
	
	convertX(OP_SET,SG_PARA0_B0,0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	tmpLine = line + 0x2d;
	
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	
	convertX(OP_SET,SG_PARA0_B0,0x2);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	tmpLine = line +0x2f;
	
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	
	convertX(OP_SET,SG_PARA0_B0,0x3);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	tmpLine = line +0x34;
	
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	
	
	
	
	convertX(OP_SET,SG_PARA0_B0,0x4);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	tmpLine = line +0x42; 
	
	
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	
	
	convertX(OP_SET,SG_PARA0_B0,0x5);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	tmpLine = line +0x88; 
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	
	
	convertX(OP_SET,SG_PARA0_B0,0x6);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	tmpLine = line +0x92; 
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	
	
	convertX(OP_SET,SG_PARA0_B0,0x7);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	tmpLine = line +0x9b; 
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	
	
	convertX(OP_SET,SG_PARA0_B0,0x8);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	tmpLine = line +0xc7; 
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	
	
	convertX(OP_SET,SG_PARA0_B0,0x9);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	tmpLine = line +0xf4; 
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	
	printf("--------------------------\n");
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	
	
	tmpLine = line +0x104;
	
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	
	
	printf("-set start------------\n");
	convertX(OP_CPY,SG_DDR_ADDR,SG_REGVAL0); 
	convertX(OP_PHY,SG_DDR_WRITE_4,PM_DDR_READ_5);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE);
	
	
	
	tmpLine = line +0xfe;	
	
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	
	
	printf("-cpy start------------\n");
	convertX(OP_PHY,SG_DDR_ADDR,PM_DDR_READ_5);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_CPY,SG_DDR_ADDR,SG_REGVAL0); 
	convertX(OP_PHY,SG_DDR_WRITE_4,PM_DDR_READ_5);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	
	
	
	tmpLine = line +0xf4;	
	
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	
	
	printf("-jmp start------------\n");
	
	
	
	convertX(OP_SET,SG_DDR_ADDR,GISC_CD_POS+0x1); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,SG_PARA0_A0,PM_DDR_READ_5);
	convertX(OP_SET,SG_PARA0_B0,0x0);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	
	
	tmpLine = line +0xea;	
	
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	convertX(OP_SET,SG_DDR_ADDR,GISC_CD_POS+0x2); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_DDR_ADDR,GISC_CD_POS+0x0); 
	convertX(OP_PHY,SG_DDR_WRITE_4,PM_DDR_READ_5);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	
	
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLine5);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	printf("drb start-------------\n");
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	convertX(OP_SET,SG_REGVAL1,0x0);
	convertX(OP_SET,SG_REGVAL0,0x7f);
	
	convertX(OP_PHY,SG_REGVAL2,PM_DDR_READ_5);
	convertX(OP_PHY,SG_DDR_ADDR,PM_DDR_READ_4);
	
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,SG_MMC_ADDR,PM_DDR_READ_5); 
	
	convertX(OP_SET,SG_2BIT_GROUP_SET_MMC_OP,SG_MMC_OP_READ);
	convertX(OP_SET,SG_2BIT_GROUP_SET_MMC_OP,SG_MMC_OP_IDLE);
	
	jmpLine6 = line;
	convertX(OP_PHY,SG_PARA0_A0,PM_1BIT_GROUP_SET);
	convertX(OP_SET,SG_PARA0_B0,PM_1BIT_G0_MMC_ACT_IDLE);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_MASK_AND);
	convertX(OP_PHY,SG_PARA0_A0,PM_PARA0_C);
	convertX(OP_SET,SG_PARA0_B0,PM_1BIT_G0_MMC_ACT_IDLE);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	
	tmpLine = line +0x5;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLine6);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	jmpLine7 = line;
	convertX(OP_SET,SG_1BIT_GROUP_SET,SG_1BIT_G0_MMC_FIFO_RO);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_PHY,SG_FMC_DATA_WRITE,PM_MMC_DATA_READ);
	
	convertX(OP_SET,SG_1BIT_GROUP_SET,SG_1BIT_G0_FMC_WO);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	
	convertX(OP_CPY,SG_PARA0_A0,SG_REGVAL1);
	
	convertX(OP_CPY,SG_PARA0_B0,SG_REGVAL0);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	tmpLine = line +0x9;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	convertX(OP_CPY,SG_PARA0_A0,SG_REGVAL1);
	convertX(OP_SET,SG_PARA0_B0,0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_REGVAL1,PM_PARA0_C);
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLine7);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	convertX(OP_CPY,SG_DDR_ADDR,SG_REGVAL2);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,SG_FMC_START_POINT,PM_DDR_READ_5); 
	 
	convertX(OP_PHY,SG_PARA0_A0,PM_DDR_READ_5);
	convertX(OP_SET,SG_PARA0_B0,0x0f000f);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_FMC_END_POINT,PM_PARA0_C);
	
	
	
	
	convertX(OP_CPY,SG_REGVAL1,SG_FMC_BRAM_ADDR);
	convertX(OP_CPY,SG_REGVAL2,SG_FMC_BRAM_ADDR);
	
	convertX(OP_CPY,SG_PARA0_A0,SG_REGVAL1);
	convertX(OP_SET,SG_PARA0_B0,0xff);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_REGVAL0,PM_PARA0_C);
	jmpLine7 = line;
	convertX(OP_CPY,SG_FMC_BRAM_ADDR,SG_REGVAL1);
	convertX(OP_SET,SG_1BIT_GROUP_SET,SG_1BIT_G0_FMC_RO);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	
	convertX(OP_CPY,SG_PARA0_A0,SG_REGVAL1);
	convertX(OP_CPY,SG_PARA0_B0,SG_REGVAL0);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	tmpLine = line +0x8;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	
	convertX(OP_SET,SG_PARA0_B0,0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_REGVAL1,PM_PARA0_C);
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLine7);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	
	
	convertX(OP_CPY,SG_FMC_BRAM_ADDR,SG_REGVAL2);
	
	
	
	convertX(OP_SET,SG_1BIT_GROUP_SET,SG_1BIT_G0_FMC_DO);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	tmpLine = line +0x96;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	
	
	
	
	printf("pts start\n");
	
		
	convertX(OP_PHY,SG_REGVAL2,PM_DDR_READ_4); 
		
	convertX(OP_PHY,SG_DDR_ADDR,PM_DDR_READ_5);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,SG_REGVAL3,PM_DDR_READ_5); 
	
		
	convertX(OP_CPY,SG_DDR_ADDR,SG_REGVAL2);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
		
	convertX(OP_PHY,SG_DDR_ADDR,PM_DDR_READ_5); 
	convertX(OP_CPY,SG_DDR_WRITE_4,SG_REGVAL3);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	tmpLine = line +0x87;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	
	printf("ptg start\n");
	
		
	convertX(OP_PHY,SG_REGVAL2,PM_DDR_READ_4); 
	
	convertX(OP_PHY,SG_DDR_ADDR,PM_DDR_READ_5);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
		
	convertX(OP_PHY,SG_DDR_ADDR,PM_DDR_READ_5);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
		
	convertX(OP_CPY,SG_DDR_ADDR,SG_REGVAL2); 
	convertX(OP_PHY,SG_DDR_WRITE_4,PM_DDR_READ_5);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	tmpLine = line +0x79;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	
	
	printf("ptg end b2m start\n");
	
	
	
	
	convertX(OP_PHY,SG_REGVAL1,PM_DDR_READ_4);
	convertX(OP_PHY,SG_DDR_ADDR,PM_DDR_READ_5);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE);
	convertX(OP_PHY,SG_MMC_ADDR,PM_DDR_READ_5); 
	convertX(OP_SET,SG_2BIT_GROUP_SET_MMC_OP,SG_MMC_OP_READ);
	convertX(OP_SET,SG_2BIT_GROUP_SET_MMC_OP,SG_MMC_OP_IDLE);
	convertX(OP_CPY,SG_DDR_ADDR,SG_REGVAL1);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE);
	convertX(OP_PHY,SG_REGVAL1,PM_DDR_READ_5);
	convertX(OP_CPY,SG_PARA0_A0,SG_REGVAL1);
	convertX(OP_SET,SG_PARA0_B0,0x7f);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_REGVAL0,PM_PARA0_C);
	
	jmpLine8 = line;
	convertX(OP_PHY,SG_PARA0_A0,PM_1BIT_GROUP_SET);
	convertX(OP_SET,SG_PARA0_B0,PM_1BIT_G0_MMC_ACT_IDLE);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_MASK_AND);
	convertX(OP_PHY,SG_PARA0_A0,PM_PARA0_C);
	convertX(OP_SET,SG_PARA0_B0,PM_1BIT_G0_MMC_ACT_IDLE);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	
	tmpLine = line +0x5;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLine8);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	
	jmpLine9 = line;
	
	convertX(OP_SET,SG_1BIT_GROUP_SET,SG_1BIT_G0_MMC_FIFO_RO);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_PHY,SG_DDR_WRITE_4,PM_MMC_DATA_READ);
	convertX(OP_CPY,SG_DDR_ADDR,SG_REGVAL1);
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_MMC_DATA_READ);
	
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	
	convertX(OP_CPY,SG_PARA0_A0,SG_REGVAL1);
	convertX(OP_CPY,SG_PARA0_B0,SG_REGVAL0);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	tmpLine = line +0x4e;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	convertX(OP_CPY,SG_PARA0_A0,SG_REGVAL1);
	convertX(OP_SET,SG_PARA0_B0,0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_REGVAL1,PM_PARA0_C);
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLine9);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	printf("b2m end m2b start\n");
	
	convertX(OP_PHY,SG_DDR_ADDR,PM_DDR_READ_4);
	convertX(OP_PHY,SG_REGVAL1,PM_DDR_READ_5);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,SG_REGVAL2,PM_DDR_READ_5);
	convertX(OP_CPY,SG_DDR_ADDR,SG_REGVAL1);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,SG_REGVAL1,PM_DDR_READ_5);
	convertX(OP_PHY,SG_PARA0_A0,PM_DDR_READ_5);
	convertX(OP_SET,SG_PARA0_B0,0x7f);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_REGVAL0,PM_PARA0_C);
	
	jmpLine9 = line;
	convertX(OP_CPY,SG_DDR_ADDR,SG_REGVAL1);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,SG_8BIT_GROUP_SET_TX0,PM_DDR_READ_5);
	
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	convertX(OP_PHY,SG_MMC_DATA_WRITE,PM_DDR_READ_5);
	convertX(OP_SET,SG_1BIT_GROUP_SET,SG_1BIT_G0_MMC_FIFO_WO);
	convertX(OP_SET,SG_1BIT_GROUP_SET,0x0);
	
	
	convertX(OP_CPY,SG_PARA0_A0,SG_REGVAL1);
	convertX(OP_CPY,SG_PARA0_B0,SG_REGVAL0);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	tmpLine = line +0x9;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	convertX(OP_CPY,SG_PARA0_A0,SG_REGVAL1);
	convertX(OP_SET,SG_PARA0_B0,0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_REGVAL1,PM_PARA0_C);
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLine9);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	
	convertX(OP_CPY,SG_MMC_ADDR,SG_REGVAL2); 
	convertX(OP_SET,SG_2BIT_GROUP_SET_MMC_OP,SG_MMC_OP_WRITE);
	convertX(OP_SET,SG_2BIT_GROUP_SET_MMC_OP,SG_MMC_OP_IDLE);
	
	jmpLine8 = line;
	convertX(OP_PHY,SG_PARA0_A0,PM_1BIT_GROUP_SET);
	convertX(OP_SET,SG_PARA0_B0,PM_1BIT_G0_MMC_ACT_IDLE);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_MASK_AND);
	convertX(OP_PHY,SG_PARA0_A0,PM_PARA0_C);
	convertX(OP_SET,SG_PARA0_B0,PM_1BIT_G0_MMC_ACT_IDLE);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	
	
	tmpLine = line +0x18;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLine8);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	printf("m2b end\n");
	
	printf("syn start\n");
	convertX(OP_SET,SG_DDR_ADDR,GISC_CD_POS+0x0); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,SG_PARA0_A0,PM_DDR_READ_5);
	convertX(OP_SET,SG_PARA0_B0,GISC_CODE_LENGTH*GISC_CODE_PER_BLK-0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_REFRESH); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	tmpLine = line + 0xa;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	convertX(OP_SET,SG_PARA0_B0,0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_DDR_WRITE_4,PM_PARA0_C);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLineSyn);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	printf("syn end\n");
	
	
	
}
void code_next_or_end(){
	
	
	
	
	
	
	
	
	convertX(OP_SET,SG_DDR_ADDR,GISC_CD_POS+0x0); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_READ); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,SG_PARA0_A0,PM_DDR_READ_5);
	
	
	convertX(OP_SET,SG_PARA0_B0,GISC_CODE_LENGTH*GISC_CODE_PER_BLK-0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_LOGIC_EQUAL);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_REFRESH); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_PHY,SG_ROM_ADDR_COND,PM_PARA0_C);
	tmpLine = line + 0xa;
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertJ();
	
	convertX(OP_SET,SG_PARA0_B0,0x1);
	convertX(OP_SET,SG_PARA0_S,PARA_SELECT_ARITH_ADD);
	convertX(OP_PHY,SG_DDR_WRITE_4,PM_PARA0_C);
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_WRITE); 
	convertX(OP_SET,SG_8BIT_GROUP_SET_DDR_OP,SG_DDR_OP_IDLE); 
	convertX(OP_SET,SG_ROM_ADDR,8*jmpLine5);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	tmpLine = line + 0x2;
	
	convertX(OP_SET,SG_ROM_ADDR,8*tmpLine);
	convertX(OP_SET,SG_ROM_ADDR_COND,SG_SET_TRUE);
	convertJ();
}
static void closeFile();
void printHeader();
void printFooter();
int main(){
	openFile();
#if defined TEST_MMC_DDR3_PHY 
code_loadMMC();
code_writeDDR();
code_checkMMC_max();
code_printOut();
jmpLineSyn = line;
code_sg_pm();
jmpLine5 = line;
code_fetch_op();
code_runtime();
code_next_or_end();
#endif
closeFile();
	return 0;
}
static void openFile(){
	#ifdef DEBUG   
	fp = fopen("test.txt", "w+");
	#else
    fp = fopen("bram.coe", "w+");
    #endif
}
void convertX(unsigned long a, unsigned long b, unsigned int c)
{
	unsigned long mix;
	mix = a << 60 | b << 32 | c;
   	
   	
	#ifdef DEBUG   
   	fprintf(fp, "convertX: %lx ", mix);
	#endif
 
   	
   	unsigned int h0,h1,h2,h3, h4,h5,h6,h7;
   	h0 = mix%256;
   	mix = mix/256;
   	h1 = mix%256;
	mix = mix/256;
	h2 = mix%256;
	mix = mix/256;
	h3 = mix%256;
	mix = mix/256;
	h4 = mix%256;
	mix = mix/256;
	h5 = mix%256;
	mix = mix/256;
	h6 = mix%256;
	mix = mix/256;
	h7 = mix%256;   
	fprintf(fp, "\'h%x:out <= \'h",line*8);
	fprintf(fp, "%x%x ",h0/16,h0%16);
	fprintf(fp, ";\n");
	fprintf(fp, "\'h%x:out <= \'h",line*8+1);
	fprintf(fp, "%x%x ",h1/16,h1%16);
	fprintf(fp, ";\n");
	fprintf(fp, "\'h%x:out <= \'h",line*8+2);
	fprintf(fp, "%x%x ",h2/16,h2%16);
	fprintf(fp, ";\n");
	fprintf(fp, "\'h%x:out <= \'h",line*8+3);
	fprintf(fp, "%x%x ",h3/16,h3%16);
	fprintf(fp, ";\n");
	fprintf(fp, "\'h%x:out <= \'h",line*8+4);
	fprintf(fp, "%x%x ",h4/16,h4%16);
	fprintf(fp, ";\n");
	fprintf(fp, "\'h%x:out <= \'h",line*8+5);
	fprintf(fp, "%x%x ",h5/16,h5%16);
	fprintf(fp, ";\n");
	fprintf(fp, "\'h%x:out <= \'h",line*8+6);
	fprintf(fp, "%x%x ",h6/16,h6%16);
	fprintf(fp, ";\n");
	fprintf(fp, "\'h%x:out <= \'h",line*8+7);
	fprintf(fp, "%x%x ",h7/16,h7%16);
	fprintf(fp, ";\n");
	
	
	
	
	
   	
	convertLog(a,b,c);
	
}
void convertLog(unsigned int a,unsigned int b,unsigned int c){
	printf("%x: ",line++);
	if(a == OP_SET){printf("OP_SET ");}
	else if(a == OP_CPY){printf("OP_CPY ");}
	else if(a == OP_JMP){printf("OP_JMP ");}
	else if(a == OP_PHY){printf("OP_PHY ");}
	if(b == SG_REGVAL0){printf("SG_REGVAL0 ");}
else if(b == SG_REGVAL1){printf("SG_REGVAL1 ");}
else if(b == SG_REGVAL2){printf("SG_REGVAL2 ");}
else if(b == SG_REGVAL3 ){printf("SG_REGVAL3 ");}
else if(b == SG_ROM_ADDR_COND){printf("SG_ROM_ADDR_COND ");}
else if(b == SG_PARA0_A0){printf("SG_PARA0_A0 ");}
else if(b == SG_PARA0_B0){printf("SG_PARA0_B0 ");}
else if(b == SG_PARA0_S){printf("SG_PARA0_S ");}
else if(b == SG_ROM_ADDR){printf("SG_ROM_ADDR ");}
else if(b == SG_REGVAL4){printf("SG_REGVAL4 ");}
else if(b == SG_REGVAL5){printf("SG_REGVAL5 ");}
else if(b == SG_REGVAL6){printf("SG_REGVAL6 ");}
else if(b == SG_REGVAL7){printf("SG_REGVAL7 ");}
else if(b == SG_DDR_WRITE_0){printf("SG_DDR_WRITE_0 ");}
else if(b == SG_DDR_WRITE_1){printf("SG_DDR_WRITE_1 ");}
else if(b == SG_DDR_WRITE_2){printf("SG_DDR_WRITE_2 ");}
else if(b == SG_DDR_WRITE_3){printf("SG_DDR_WRITE_3 ");}
else if(b == SG_DDR_WRITE_4){printf("SG_DDR_WRITE_4 ");}
else if(b == SG_DDR_WRITE_5){printf("SG_DDR_WRITE_5 ");}
else if(b == SG_DDR_ADDR){printf("SG_DDR_ADDR ");}
else if(b == SG_NOR_ADDR){printf("SG_NOR_ADDR ");}
else if(b == SG_MMC_DATA_WRITE){printf("SG_MMC_DATA_WRITE ");}
else if(b == SG_MMC_ADDR){printf("SG_MMC_ADDR ");}
else if(b == SG_GPIO_GROUP_SET){printf("SG_GPIO_GROUP_SET ");}
else if(b == SG_FMC_DATA_WRITE){printf("SG_FMC_DATA_WRITE ");}
else if(b == SG_FMC_START_POINT){printf("SG_FMC_START_POINT ");}
else if(b == SG_FMC_END_POINT){printf("SG_FMC_END_POINT ");}
else if(b == SG_TWI_REGISTER){printf("SG_TWI_REGISTER ");}
else if(b == SG_TWI_DATA_WRITE){printf("SG_TWI_DATA_WRITE ");}
else if(b == SG_1BIT_GROUP_SET){printf("SG_1BIT_GROUP_SET ");}
else if(b == SG_8BIT_GROUP_SET_TX0){printf("SG_8BIT_GROUP_SET_TX0 ");}
else if(b == SG_8BIT_GROUP_SET_TX1){printf("SG_8BIT_GROUP_SET_TX1 ");}
else if(b == SG_8BIT_GROUP_SET_DDR_OP){printf("SG_8BIT_GROUP_SET_DDR_OP ");}
else if(b == SG_2BIT_GROUP_SET_MMC_OP){printf("SG_2BIT_GROUP_SET_MMC_OP ");}
	if(a == OP_PHY){
		if(c == PM_PARA0_C){printf("PM_PARA0_C ");}
		else if(c == PM_DDR_READ_0){printf("PM_DDR_READ_0 ");}
		else if(c == PM_DDR_READ_1){printf("PM_DDR_READ_1 ");}
		else if(c == PM_DDR_READ_2){printf("PM_DDR_READ_2 ");}
		else if(c == PM_DDR_READ_3){printf("PM_DDR_READ_3 ");}
		else if(c == PM_DDR_READ_4){printf("PM_DDR_READ_4 ");}
		else if(c == PM_DDR_READ_5){printf("PM_DDR_READ_5 ");}
		else if(c == PM_NOR_DATA){printf("PM_NOR_DATA ");}
		else if(c == PM_MMC_DATA_READ){printf("PM_MMC_DATA_READ ");}
		else if(c == PM_TWI_DATA_READ){printf("PM_TWI_DATA_READ ");}
		else if(c == PM_1BIT_GROUP_SET){printf("PM_1BIT_GROUP_SET ");}
		else if(c == PM_8BIT_GROUP_GET_RX0){printf("PM_8BIT_GROUP_GET_RX0 ");}
		else if(c == PM_8BIT_GROUP_GET_RX1){printf("PM_8BIT_GROUP_GET_RX1 ");}
	}else if(a == OP_SET){
		if(b == SG_PARA0_S){
				 if(c == PARA_SELECT_MASK_AND){printf("PARA_SELECT_MASK_AND ");}
			else if(c == PARA_SELECT_MASK_OR){printf("PARA_SELECT_MASK_OR ");}
			else if(c == PARA_SELECT_ARITH_SUB){printf("PARA_SELECT_ARITH_SUB ");}
			else if(c == PARA_SELECT_LOGIC_EQUAL){printf("PARA_SELECT_LOGIC_EQUAL ");}
			else if(c == PARA_SELECT_ARITH_ADD){printf("PARA_SELECT_ARITH_ADD ");}
			else if(c == PARA_SELECT_LOGIC_GREATER){printf("PARA_SELECT_LOGIC_GREATER ");}
			else if(c == PARA_SELECT_LOGIC_SMALLER){printf("PARA_SELECT_LOGIC_SMALLER ");}
			else if(c == PARA_SELECT_ARITH_MUL){printf("PARA_SELECT_ARITH_MUL ");}
			else if(c == PARA_SELECT_ARITH_DIV){printf("PARA_SELECT_ARITH_DIV ");}
			else if(c == PARA_SELECT_LOGIC_AND){printf("PARA_SELECT_LOGIC_AND ");}
			else if(c == PARA_SELECT_LOGIC_OR){printf("PARA_SELECT_LOGIC_OR ");}
			else if(c == PARA_SELECT_ARITH_MOD){printf("PARA_SELECT_ARITH_MOD ");}
		}if(b == SG_ROM_ADDR){
			printf("8*%x ",c/8);
		}else {
			printf("%x ",c);
		}
		
	}else if(a == OP_CPY){
		if(c == SG_REGVAL0){printf("SG_REGVAL0 ");}
	else if(c == SG_REGVAL1){printf("SG_REGVAL1 ");}
	else if(c == SG_REGVAL2){printf("SG_REGVAL2 ");}
	else if(c == SG_REGVAL3 ){printf("SG_REGVAL3 ");}
	else if(c == SG_ROM_ADDR_COND){printf("SG_ROM_ADDR_COND ");}
	else if(c == SG_PARA0_A0){printf("SG_PARA0_A0 ");}
	else if(c == SG_PARA0_B0){printf("SG_PARA0_B0 ");}
	else if(c == SG_PARA0_S){printf("SG_PARA0_S ");}
	else if(c == SG_ROM_ADDR){printf("SG_ROM_ADDR ");}
	else if(c == SG_REGVAL4){printf("SG_REGVAL4 ");}
	else if(c == SG_REGVAL5){printf("SG_REGVAL5 ");}
	else if(c == SG_REGVAL6){printf("SG_REGVAL6 ");}
	else if(c == SG_REGVAL7){printf("SG_REGVAL7 ");}
	else if(c == SG_DDR_WRITE_0){printf("SG_DDR_WRITE_0 ");}
	else if(c == SG_DDR_WRITE_1){printf("SG_DDR_WRITE_1 ");}
	else if(c == SG_DDR_WRITE_2){printf("SG_DDR_WRITE_2 ");}
	else if(c == SG_DDR_WRITE_3){printf("SG_DDR_WRITE_3 ");}
	else if(c == SG_DDR_WRITE_4){printf("SG_DDR_WRITE_4 ");}
	else if(c == SG_DDR_WRITE_5){printf("SG_DDR_WRITE_5 ");}
	else if(c == SG_DDR_ADDR){printf("SG_DDR_ADDR ");}
	else if(c == SG_NOR_ADDR){printf("SG_NOR_ADDR ");}
	else if(c == SG_MMC_DATA_WRITE){printf("SG_MMC_DATA_WRITE ");}
	else if(c == SG_MMC_ADDR){printf("SG_MMC_ADDR ");}
	else if(c == SG_GPIO_GROUP_SET){printf("SG_GPIO_GROUP_SET ");}
	else if(c == SG_FMC_DATA_WRITE){printf("SG_FMC_DATA_WRITE ");}
	else if(c == SG_FMC_START_POINT){printf("SG_FMC_START_POINT ");}
	else if(c == SG_FMC_END_POINT){printf("SG_FMC_END_POINT ");}
	else if(c == SG_TWI_REGISTER){printf("SG_TWI_REGISTER ");}
	else if(c == SG_TWI_DATA_WRITE){printf("SG_TWI_DATA_WRITE ");}
	else if(c == SG_1BIT_GROUP_SET){printf("SG_1BIT_GROUP_SET ");}
	else if(c == SG_8BIT_GROUP_SET_TX0){printf("SG_8BIT_GROUP_SET_TX0 ");}
	else if(c == SG_8BIT_GROUP_SET_TX1){printf("SG_8BIT_GROUP_SET_TX1 ");}
	else if(c == SG_8BIT_GROUP_SET_DDR_OP){printf("SG_8BIT_GROUP_SET_DDR_OP ");}
	else if(c == SG_2BIT_GROUP_SET_MMC_OP){printf("SG_2BIT_GROUP_SET_MMC_OP ");}
	}
		printf("\n");
}
void convertB(unsigned long a, unsigned long b, unsigned int c)
{
	
	
	
	convertX(a,b,c);
}
void convertJ()
{
	#ifdef DEBUG
	fprintf(fp, "convertJ: 1010101010101000 ");
	#endif
	
	fprintf(fp, "\'h%x:out <= \'h10 ;\n",line*8);
	fprintf(fp, "\'h%x:out <= \'h10 ;\n",line*8+1);
	fprintf(fp, "\'h%x:out <= \'h10 ;\n",line*8+2);
	fprintf(fp, "\'h%x:out <= \'h10 ;\n",line*8+3);
	fprintf(fp, "\'h%x:out <= \'h10 ;\n",line*8+4);
	fprintf(fp, "\'h%x:out <= \'h10 ;\n",line*8+5);
	fprintf(fp, "\'h%x:out <= \'h10 ;\n",line*8+6);
	fprintf(fp, "\'h%x:out <= \'h00 ;\n",line*8+7);
	printf("%x: ",line++);
	printf("OP_JMP\n");
}
static void closeFile(){
	fclose(fp);
};
void printHeader(){
   fprintf(fp, "memory_initialization_radix=16;\nmemory_initialization_vector=");
}
void printFooter(){
   fprintf(fp, ";\n");
}
